### ISSUE TITLE
Undefined index when using 'connection' option

### ISSUE THREAD

**Issue by thewunder** [cakephp/phinx#1170]
This is a regression after updating to 0.9.0, looks like the connection option (the pdo instance) is not getting set on the adapter.

```
Error: Undefined index: host on line 89 of /vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php in /src/Lifestyle/ErrorHandler.php:53
Stack trace:#0 /vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php(89): Lifestyle\\ErrorHandler->errorHandler(8, 'Undefined index...', '/var/www/dev_20...', 89, Array)
#1 /vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(88): Phinx\\Db\\Adapter\\MysqlAdapter->connect()
#2 /vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(128): Phinx\\Db\\Adapter\\PdoAdapter->getConnection()
#3 /vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(146): Phinx\\Db\\Adapter\\PdoAdapter->query('SELECT * FROM p...')
#4 /vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(231): Phinx\\Db\\Adapter\\PdoAdapter->fetchAll('SELECT * FROM p...')
#5 /vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(208): Phinx\\Db\\Adapter\\PdoAdapter->getVersionLog()
#6 /vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(215): Phinx\\Db\\Adapter\\PdoAdapter->getVersions()
#7 /vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(258): Phinx\\Db\\Adapter\\AdapterWrapper->getVersions()
#8 /vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(300): Phinx\\Migration\\Manager\\Environment->getVersions()
#9 /vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(114): Phinx\\Migration\\Manager->migrate('dev', NULL)
#10 /vendor/symfony/console/Command/Command.php(264): Phinx\\Console\\Command\\Migrate->execute(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\StreamOutput))
#11 /vendor/symfony/console/Application.php(888): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Symfony\\Component\\Console\\Output\\StreamOutput))
```

**Comment by thewunder** [comment]
Snippet from my phinx.php file

```php
return [
    'paths'                     => [
        'migrations'    => $app['base_dir'] . 'db' . DIRECTORY_SEPARATOR . 'migrations',
        'seeds'         => $app['base_dir'] . 'db' . DIRECTORY_SEPARATOR . 'seeds'
    ],
    'default_database'          => $app['environment_name'],
    'environments'              => [
        $app['environment_name']    => [
            'name'          => $app['db_name'],
            'connection'    => $app['pdo']
        ]
    ]
];
```

**Comment by swiffer** [comment]
Yes, Same here. Update broke phinx due to this.

**Comment by lorenzo** [comment]
@thewunder @swiffer would any of you like to send a pull request with the fix?

**Comment by swiffer** [comment]
pull request is open 😄 

#1171

**Comment by swiffer** [comment]
think the code deleted here was not save to remove completly

https://github.com/cakephp/phinx/compare/v0.8.1...master#diff-1ba3851ff60f2161d4cf1849606cd4a3L104

**Comment by thewunder** [comment]
@lorenzo I would consider a release just for this fix.  I'm sure this makes 0.9.0 unusable for a decent portion of users.

**Comment by swiffer** [comment]
Yes, having a fix Release would bei great!

**Comment by lorenzo** [comment]
Yeah, I was planning on doing that, but did not get enough time yesterday to finish it.
