### ISSUE TITLE
Regression: Passing in PDO does not work in 0.9.1

### ISSUE THREAD

**Issue by adduc** [cakephp/phinx#1273]
Passing an existing PDO connection to Phinx through the PHP config worked in 0.8.x, but appears to have broke in 0.9.x (testing against the 0.9.1 release).

Runing `phinx migrate` with 0.9.1, I receive the following exception:
```
PHP Fatal error:  Uncaught Error: Call to a member function hasOption() on null in APP/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AbstractAdapter.php:248
Stack trace:
#0 APP/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(126): Phinx\Db\Adapter\AbstractAdapter->isDryRunEnabled()
#1 APP/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php(299): Phinx\Db\Adapter\PdoAdapter->execute('CREATE TABLE `p...')
#2 APP/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(609): Phinx\Db\Adapter\MysqlAdapter->createTable(Object(Phinx\Db\Table))
#3 APP/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(697): Phinx\Db\Table->create()
#4 APP/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AbstractAdapter.php(218): Phinx\Db\Table->save()
```

Running `phinx migrate` using 0.8.1 with the same configuration, command, and database environment, the migration runs without issue.

**phinx.php**:
```php
<?php

// <Bootstrap code, includes, etc.>

$config = [
    'paths' => [
        'migrations' => '%%PHINX_CONFIG_DIR%%/migrations',
        'seeds' => '%%PHINX_CONFIG_DIR%%/seeds'
    ],
    'environments' => [
        'default_migration_table' => 'phinxlog',
        'default_database' => 'development',
        'development' => [
            'name' => '%%PHINX_DB_NAME%%',
            'connection' => $db->getConnection(),
        ]
    ]
];

return $config;
```

**Comment by rask** [comment]
Seeing the same issue here. First time using Phinx so might be just me. I'll try the 0.8 version and see what happens.

**Comment by hazolsky** [comment]
This seems to me like a duplicate of https://github.com/cakephp/phinx/pull/1181

**Comment by adduc** [comment]
Yup, it's the same issue.
