### ISSUE TITLE
Error: Call to a member function fetch() on array in .../vendors/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:204

### ISSUE THREAD

**Issue by niel** [cakephp/phinx#1546]
I was doing: 

phinx migrate -e dev --dry-run

Stack trace:
#0 .../vendors/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php(205): Phinx\Db\Adapter\PdoAdapter->fetchRow('SELECT TABLE_NA...')
#1 .../vendors/robmorgan/phinx/src/Phinx/Db/Adapter/AbstractAdapter.php(204): Phinx\Db\Adapter\MysqlAdapter->hasTable('phinxlog')
#2 .../vendors/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(105): Phinx\Db\Adapter\AbstractAdapter->hasSchemaTable()
#3 .../vendors/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(88): Phinx\Db\Adapter\PdoAdapter->setConnection(Object(nzedb\db\DB))
#4 .../vendors/robmorgan/phinx/src/Phinx/Db/Adapter/AbstractAdapter.php(72): Phinx\Db\Adapter\PdoAdapter->setOptions(Array)
#5 .../vendors/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterFactory.php(133): Phinx\Db\Adapter\AbstractAdapter->__construct(Array)
#6 .../vendors/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(380): Phinx\Db\Adapter\AdapterFactory->getAdapter('mysql', Array)
#7 .../vendors/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(292): Phinx\Migration\Manager\Environment->getAdapter()
#8 .../vendors/robmorgan/phinx/src/Phinx/Migration/Manager.php(317): Phinx\Migration\Manager\Environment->getVersions()
#9 .../vendors/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate('dev', NULL, false)
#10 .../vendors/symfony/console/Command/Command.php(255): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 .../vendors/symfony/console/Application.php(917): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 .../vendors/symfony/console/Application.php(269): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 .../vendors/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(88): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 .../vendors/symfony/console/Application.php(145): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 .../vendors/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#16 {main}

**Comment by MasterOdin** [comment]
Would you be able to provide your migration file and configuration that triggered this error? I've been unable to replicate this error using the standard mysql setup through yml or php file, and that unless you're providing your own connection, the line in question is only possible to return a PDOStatement or false, never an array.

**Comment by othercorey** [comment]
Closing due to lack of activity or out of scope. If there is new interest, please open a PR.
