### ISSUE TITLE
Latest symfony changes cause exception when phinx is run

### ISSUE THREAD

**Issue by angelk** [cakephp/phinx#1594]
Check latest updates from symfony - https://github.com/symfony/symfony/pull/33332/files#diff-8e80595663798837db1b033187835535R460
This changes require the command to have a name.

Phinx code assign default name if there is none
`$this->setName($this->getName() ?: 'init')`
This will throw exception with the new code.

```
─ $ ▶ ./vendor/bin/phinx 
PHP Fatal error:  Uncaught Symfony\Component\Console\Exception\LogicException: The command defined in "Phinx\Console\Command\Init" cannot have an empty name. in /home/potaka/Projects/krivaGPS/script/migration/vendor/symfony/console/Command/Command.php:453
Stack trace:
#0 /home/potaka/Projects/krivaGPS/script/migration/vendor/robmorgan/phinx/src/Phinx/Console/Command/Init.php(47): Symfony\Component\Console\Command\Command->getName()
#1 /home/potaka/Projects/krivaGPS/script/migration/vendor/symfony/console/Command/Command.php(77): Phinx\Console\Command\Init->configure()
#2 /home/potaka/Projects/krivaGPS/script/migration/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(60): Symfony\Component\Console\Command\Command->__construct()
#3 /home/potaka/Projects/krivaGPS/script/migration/vendor/robmorgan/phinx/app/phinx.php(36): Phinx\Console\PhinxApplication->__construct()
#4 /home/potaka/Projects/krivaGPS/script/migration/vendor/robmorgan/phinx/bin/phinx(27): require('/home/potaka/Pr...')
#5 {main}
  thrown in /home/potaka/Projects/krivaGPS/script/migration/vendor/symfony/console/Command/Command.php on line 453
```

**Comment by angelk** [comment]
Surround the phinx code with try-catch should do the work, but it is ugly.

**Comment by dereuromark** [comment]
Fixed in master. See historie.
