### ISSUE TITLE
"Phinx\Console\Command\Init" cannot have an empty name (symfony/console >= 4.3.4)

### ISSUE THREAD

**Issue by tarnagas** [cakephp/phinx#1597]
```
PHP Fatal error:  Uncaught Symfony\Component\Console\Exception\LogicException: The command defined in "Phinx\Console\Command\Init" cannot have an empty name. in /var/www/localhost/htdocs/vendor/symfony/console/Command/Command.php:453
Stack trace:
#0 /var/www/localhost/htdocs/vendor/robmorgan/phinx/src/Phinx/Console/Command/Init.php(47): Symfony\Component\Console\Command\Command->getName()
#1 /var/www/localhost/htdocs/vendor/symfony/console/Command/Command.php(77): Phinx\Console\Command\Init->configure()
#2 /var/www/localhost/htdocs/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(60): Symfony\Component\Console\Command\Command->__construct()
#3 /var/www/localhost/htdocs/vendor/nartex/nx-phinx/bin/nx-phinx(12): Phinx\Console\PhinxApplication->__construct()
#4 {main}
  thrown in /var/www/localhost/htdocs/vendor/symfony/console/Command/Command.php on line 453
```

With composer json:

```json
{
    "require": {
        "robmorgan/phinx": "~0.10"
    },
}
```

```sh
composer info | grep console
symfony/console                     v4.3.4              Symfony Console C...
```

When ``symfony/console`` is downgraded to ``v4.3.3``:

```json
{
    "require": {
        "robmorgan/phinx": "~0.10",
        "symfony/console": "=4.3.3"
    },
}
```

It works. I guess  ``symfony/console`` `` v4.3.4`` introduces a breaking change with ``phinx``.

**Comment by dereuromark** [comment]
We released a fix today.

**Comment by tarnagas** [comment]
see: https://github.com/cakephp/phinx/pull/1596
