### ISSUE TITLE
0.11.15 error

### ISSUE THREAD

**Issue by Shardj** [cakephp/phinx#1724]
0.11.14 works fine so I've reverted for now

```
InvalidArgumentException: You cannot enable an auto incrementing ID field and a primary key in /srv/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php:242
Stack trace:
#0 /srv/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(366): Phinx\Db\Adapter\MysqlAdapter->createTable(Object(Phinx\Db\Table\Table), Array, Array)
#1 /srv/www/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TimedOutputAdapter.php(120): Phinx\Db\Adapter\AdapterWrapper->createTable(Object(Phinx\Db\Table\Table), Array, Array)
#2 /srv/www/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(148): Phinx\Db\Adapter\TimedOutputAdapter->createTable(Object(Phinx\Db\Table\Table), Array, Array)
#3 /srv/www/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(722): Phinx\Db\Plan\Plan->execute(Object(Phinx\Db\Adapter\TimedOutputAdapter))
#4 /srv/www/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(616): Phinx\Db\Table->executeActions(false)
#5 /srv/www/database/src/Migration/20180911155431_add_user_enabled_history_table.php(27): Phinx\Db\Table->create()
#6 /srv/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(108): Pi\Database\Migration\AddUserEnabledHistoryTable->up()
#7 /srv/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(374): Phinx\Migration\Manager\Environment->executeMigration(Object(Pi\Database\Migration\AddUserEnabledHistoryTable), 'up', false)
#8 /srv/www/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(347): Phinx\Migration\Manager->executeMigration('default', Object(Pi\Database\Migration\AddUserEnabledHistoryTable), 'up', false)
#9 /srv/www/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(120): Phinx\Migration\Manager->migrate('default', 20200309153700, false)
#10 /srv/www/vendor/symfony/console/Command/Command.php(255): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /srv/www/vendor/symfony/console/Application.php(1001): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /srv/www/vendor/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /srv/www/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(69): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /srv/www/vendor/symfony/console/Application.php(147): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /srv/www/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#16 {main}
```

Here's the class it failed on:

```
<?php
namespace Pi\Database\Migration;

use Phinx\Db\Adapter\MysqlAdapter;
use Phinx\Migration\AbstractMigration;

/**
 *create user_enabled_history table and populate the table with existing data from user table
 */
class AddUserEnabledHistoryTable extends AbstractMigration {

    public function up(): void {
        $table = $this->table("user_enabled_history", ['id' => true, 'primary_key' => ["id"]]);
        $table->addColumn('user_id', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR])
            ->addColumn('start_date', 'datetime', ['null' => true])
            ->addColumn('end_date', 'datetime', ['null' => true])
            ->addForeignKey(
                'user_id',
                "user",
                'id',
                [
                    'constraint' => "fk_user_id",
                    'update' => "RESTRICT",
                    'delete' => "CASCADE"
                ]
            )
            ->create();

        $this->execute(
            'INSERT INTO user_enabled_history (user_id, start_date, end_date)
                 SELECT u.id, u.created_date, now()
                 FROM user AS u WHERE u.enabled = 0'
        );

        $this->execute(
            'INSERT INTO user_enabled_history (user_id, start_date)
                 SELECT u.id, u.created_date
                 FROM user AS u WHERE u.enabled = 1'
        );
    }

    public function down(): void {
        $this->table('user_enabled_history')->drop()->save();
    }
}
```

**Comment by dereuromark** [comment]
Please see https://github.com/cakephp/phinx/pull/1716
The code you are using seems to the issue -  and this just makes the issue visible.
So best to fix your migration file, then the exception should go away.

**Comment by Shardj** [comment]
Okay thanks

**Comment by Shardj** [comment]
I'll add, I don't really like the change linked. I prefer the way I wrote it in my pasted code where I'm explicit with the primary key

**Comment by MasterOdin** [comment]
To be clear, by default, if you specify `'id' => true` (or any string value), it implicitly sets the value of `primary_key` to that field. So you would just change `$this->table("user_enabled_history", ['id' => true, 'primary_key' => ["id"]]);` to be `$this->table("user_enabled_history", ['id' => true]);` and the table created will be the same as before (where `primary_key` is just implicitly set to `id`).

**Comment by dereuromark** [comment]
If they are the same, then I also don't see the need to throw any error.
