### ISSUE TITLE
Phinx 0.12.1 Column already exists

### ISSUE THREAD

**Issue by cnizzardini** [cakephp/phinx#1787]
Encountering the following error:

> PDOException: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'id' in /var/www/personal/easyupp/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:185

**Environment**

CakePHP 4.0.7, Phinx 0.12.1, Migrations 3.0.0 on Ubuntu 18.04 LTS with MySQL 5.7 and PHP-FPM 7.2

**Reproduce**

`bin/cake migrations create PostalCodes`

```php
<?php
declare(strict_types=1);

use Migrations\AbstractMigration;

class PostalCodes extends AbstractMigration
{
    /**
     * Change Method.
     *
     * More information on this method is available here:
     * https://book.cakephp.org/phinx/0/en/migrations.html#the-change-method
     * @return void
     */
    public function up()
    {
        $table = $this->table('postal_codes');
        $table
            ->addColumn('id', 'integer', [
                'autoIncrement' => true,
                'default' => null,
                'limit' => 10,
                'null' => false,
                'signed' => false
            ])
            ->addPrimaryKey(['id'])
            ->addColumn('postal_code', 'char', [
                'default' => '',
                'limit' => 5,
                'null' => false,
            ])
            ->addColumn('city', 'string', [
                'default' => null,
                'limit' => 64,
                'null' => false,
            ])
            ->addColumn('state', 'char', [
                'default' => null,
                'limit' => 2,
                'null' => false,
            ])
            ->create();
    }
}
```

Then run `bin/cake migrations migrate`

**Expected**

New table is created.

**Actual**

```
chris@chris-x1 /v/w/p/easyupp> bin/cake migrations migrate
using migration paths 
 - /var/www/personal/easyupp/config/Migrations
using seed paths 
 - /var/www/personal/easyupp/config/Seeds
using environment default
using adapter mysql
using database easyupp
ordering by creation time

 == 20200516135323 PostalCodes: migrating
PDOException: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'id' in /var/www/personal/easyupp/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:185
Stack trace:
#0 /var/www/personal/easyupp/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(185): PDO->exec('CREATE TABLE `p...')
#1 /var/www/personal/easyupp/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php(335): Phinx\Db\Adapter\PdoAdapter->execute('CREATE TABLE `p...')
#2 /var/www/personal/easyupp/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(374): Phinx\Db\Adapter\MysqlAdapter->createTable(Object(Phinx\Db\Table\Table), Array, Array)
#3 /var/www/personal/easyupp/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TimedOutputAdapter.php(120): Phinx\Db\Adapter\AdapterWrapper->createTable(Object(Phinx\Db\Table\Table), Array, Array)
#4 /var/www/personal/easyupp/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(374): Phinx\Db\Adapter\TimedOutputAdapter->createTable(Object(Phinx\Db\Table\Table), Array, Array)
#5 /var/www/personal/easyupp/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(148): Phinx\Db\Adapter\AdapterWrapper->createTable(Object(Phinx\Db\Table\Table), Array, Array)
#6 /var/www/personal/easyupp/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(722): Phinx\Db\Plan\Plan->execute(Object(Migrations\CakeAdapter))
#7 /var/www/personal/easyupp/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(616): Phinx\Db\Table->executeActions(false)
#8 /var/www/personal/easyupp/vendor/cakephp/migrations/src/Table.php(138): Phinx\Db\Table->create()
#9 /var/www/personal/easyupp/config/Migrations/20200516135323_PostalCodes.php(46): Migrations\Table->create()
#10 /var/www/personal/easyupp/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(112): PostalCodes->up()
#11 /var/www/personal/easyupp/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(377): Phinx\Migration\Manager\Environment->executeMigration(Object(PostalCodes), 'up', false)
#12 /var/www/personal/easyupp/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(350): Phinx\Migration\Manager->executeMigration('default', Object(PostalCodes), 'up', false)
#13 /var/www/personal/easyupp/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(123): Phinx\Migration\Manager->migrate('default', 20200516135323, false)
#14 /var/www/personal/easyupp/vendor/cakephp/migrations/src/Command/Phinx/CommandTrait.php(37): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/personal/easyupp/vendor/cakephp/migrations/src/Command/Phinx/Migrate.php(85): Migrations\Command\Phinx\Migrate->parentExecute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/personal/easyupp/vendor/symfony/console/Command/Command.php(255): Migrations\Command\Phinx\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/personal/easyupp/vendor/symfony/console/Application.php(912): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/personal/easyupp/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand(Object(Migrations\Command\Phinx\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/personal/easyupp/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/personal/easyupp/vendor/cakephp/migrations/src/Command/MigrationsCommand.php(126): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/personal/easyupp/vendor/cakephp/cakephp/src/Console/BaseCommand.php(175): Migrations\Command\MigrationsCommand->execute(Object(Cake\Console\Arguments), Object(Cake\Console\ConsoleIo))
#22 /var/www/personal/easyupp/vendor/cakephp/migrations/src/Command/MigrationsCommand.php(198): Cake\Console\BaseCommand->run(Array, Object(Cake\Console\ConsoleIo))
#23 /var/www/personal/easyupp/vendor/cakephp/cakephp/src/Console/CommandRunner.php(336): Migrations\Command\MigrationsCommand->run(Array, Object(Cake\Console\ConsoleIo))
#24 /var/www/personal/easyupp/vendor/cakephp/cakephp/src/Console/CommandRunner.php(171): Cake\Console\CommandRunner->runCommand(Object(Migrations\Command\MigrationsMigrateCommand), Array, Object(Cake\Console\ConsoleIo))
#25 /var/www/personal/easyupp/bin/cake.php(12): Cake\Console\CommandRunner->run(Array)
#26 {main}
```

**Comment by dereuromark** [comment]
This is documented - https://book.cakephp.org/phinx/0/en/migrations.html#creating-a-table

**Comment by MasterOdin** [comment]
Per the note in [Creating a Table](https://book.cakephp.org/phinx/0/en/migrations.html#creating-a-table), Phinx automatically adds an `id` column itself to any table that's created. If you wish to override that behavior (say by making your own `id` column), you'll need to do:

```php
        $table = $this->table('postal_codes', ['id' => false, 'primary_key' => 'id']);
```

**Comment by dereuromark** [comment]
^^ same second.

**Comment by cnizzardini** [comment]
Thanks guys. Did this change recently? I have migrations from not long ago that specify the `id` column.

**Comment by cnizzardini** [comment]
I see actually at the top of that Intial class I created that there is an `$autoId = false` class property. So thats probably why.

**Comment by cnizzardini** [comment]
I can't say that I like phinx auto adding that for me, but now I know to tell it to ignore.

**Comment by MasterOdin** [comment]
Looks like since at least version 0.6.0 (which was released in 2016 or so). The `$autoId` variable is not part of standard phinx, so it sounds like you might be using a custom Migration base as well than stock phinx.
