### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Symfony\Component\Console\Application' not found

### ISSUE THREAD

**Issue by chrissound** [cakephp/phinx#1790]
Not sure if this is a composer2nix issue but I'm running into the below error for b417acfa775a4e65801afbe1b5c7eefd1917aea8:

```
phinx

Fatal error: Uncaught Error: Class 'Symfony\Component\Console\Application' not found in /nix/store/jhlk6rxwy990hazy7qp7s0vnkis7pqp8-composer-robmorgan-phinx/share/php/composer-robmorgan-phinx/src/Phinx/Console/PhinxApplication.php:29
Stack trace:
#0 /nix/store/jhlk6rxwy990hazy7qp7s0vnkis7pqp8-composer-robmorgan-phinx/share/php/composer-robmorgan-phinx/vendor/composer/ClassLoader.php(444): include()
#1 /nix/store/jhlk6rxwy990hazy7qp7s0vnkis7pqp8-composer-robmorgan-phinx/share/php/composer-robmorgan-phinx/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/nix/store/jhlk...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Phinx\\Console\\P...')
#3 /nix/store/jhlk6rxwy990hazy7qp7s0vnkis7pqp8-composer-robmorgan-phinx/share/php/composer-robmorgan-phinx/app/phinx.php(36): spl_autoload_call('Phinx\\Console\\P...')
#4 /nix/store/jhlk6rxwy990hazy7qp7s0vnkis7pqp8-composer-robmorgan-phinx/share/php/composer-robmorgan-phinx/bin/phinx(27): require('/nix/store/jhlk...')
#5 {main}
  thrown in /nix/store/jhlk6rxwy990hazy7qp7s0vnkis7pqp8-composer-robmorgan-phinx/share/php/composer-robmorgan-phinx/src/Phinx/Console/PhinxApplication.php on line 29
```

**Comment by dereuromark** [comment]
This sounds like a composer autoloader issue not directly relevant to this package.

**Comment by MasterOdin** [comment]
I could replicate this error by deleting `vendor/symfony/console/Application.php` and then attempting to use phinx. It looks like it's able to locate the composer vendor directory, and then just not able to find that particular package / file then.

**Comment by othercorey** [comment]
@chrissound Can you give any information on why this is a phinx issue?
