### ISSUE TITLE
RuntimeException: Adapter "postgresql" has not been registered in 

### ISSUE THREAD

**Issue by chrissound** [cakephp/phinx#1791]
composer lock file: https://gist.github.com/chrissound/705d8d7a2ad513fff835bc5ed5cb249d

```
RuntimeException: Adapter "postgresql" has not been registered in /build/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterFactory.php:98
Stack trace:
#0 /build/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterFactory.php(117): Phinx\Db\Adapter\AdapterFactory->getClass('postgresql')
#1 /build/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(351): Phinx\Db\Adapter\AdapterFactory->getAdapter('postgresql', Array)
#2 /build/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(259): Phinx\Migration\Manager\Environment->getAdapter()
#3 /build/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(306): Phinx\Migration\Manager\Environment->getVersions()
#4 /build/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(123): Phinx\Migration\Manager->migrate('development', NULL, false)
#5 /build/vendor/symfony/console/Command/Command.php(255): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /build/vendor/symfony/console/Application.php(912): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /build/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /build/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(69): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /build/vendor/symfony/console/Application.php(140): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /build/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#11 {main}
```

**Comment by chrissound** [comment]
Had `adapter: postgresql` instead of `adapter: pgsql`.
