### ISSUE TITLE
phinx - Migration error

### ISSUE THREAD

**Issue by KolRoma** [cakephp/phinx#1887]
I'll try use bin/cake migrations migrate, but get error
My ```DATABASE_URL="mysql://root:qwerty@localhost/database?encoding=utf8&timezone=UTC&cacheMetadata=true&quoteIdentifiers=false&persistent=false"```
```using migration paths 
 - /application/config/Migrations
using seed paths 
 - /application/config/Seeds
Exception: There was a problem connecting to the database: SQLSTATE[HY000] [2002] No such file or directory in [/application/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php, line 82]
2020-09-28 12:41:27 Error: [InvalidArgumentException] There was a problem connecting to the database: SQLSTATE[HY000] [2002] No such file or directory in /application/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php on line 82
Stack Trace:
#0 /application/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/MysqlAdapter.php(116): Phinx\Db\Adapter\PdoAdapter->createPdoConnection()
#1 /application/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(148): Phinx\Db\Adapter\MysqlAdapter->connect()
#2 /application/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(496): Phinx\Db\Adapter\PdoAdapter->getConnection()
#3 /application/vendor/cakephp/migrations/src/CakeAdapter.php(56): Phinx\Db\Adapter\AdapterWrapper->getConnection()
#4 /application/vendor/cakephp/migrations/src/Command/CommandTrait.php(78): Migrations\CakeAdapter->__construct()
#5 /application/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(63): Migrations\Command\Migrate->bootstrap()
#6 /application/vendor/cakephp/migrations/src/Command/CommandTrait.php(35): Phinx\Console\Command\Migrate->execute()
#7 /application/vendor/cakephp/migrations/src/Command/Migrate.php(66): Migrations\Command\Migrate->parentExecute()
#8 /application/vendor/symfony/console/Command/Command.php(255): Migrations\Command\Migrate->execute()
#9 /application/vendor/symfony/console/Application.php(912): Symfony\Component\Console\Command\Command->run()
#10 /application/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand()
#11 /application/vendor/symfony/console/Application.php(140): Symfony\Component\Console\Application->doRun()
#12 /application/vendor/cakephp/migrations/src/Shell/MigrationsShell.php(108): Symfony\Component\Console\Application->run()
#13 /application/vendor/cakephp/cakephp/src/Console/Shell.php(531): Migrations\Shell\MigrationsShell->main()
#14 /application/vendor/cakephp/migrations/src/Shell/MigrationsShell.php(169): Cake\Console\Shell->runCommand()
#15 /application/vendor/cakephp/cakephp/src/Console/CommandRunner.php(385): Migrations\Shell\MigrationsShell->runCommand()
#16 /application/vendor/cakephp/cakephp/src/Console/CommandRunner.php(162): Cake\Console\CommandRunner->runShell()
#17 /application/bin/cake.php(12): Cake\Console\CommandRunner->run()
#18 {main}
```

What's wrong?

**Comment by dereuromark** [comment]
This might be more a ticket for migrations plugin:  https://github.com/cakephp/migrations/
But even then this looks more like a support issue for the slack channel or alike.

**Comment by garas** [comment]
`SQLSTATE[HY000] [2002] No such file or directory` means PHP tries to use Unix socket file to connect to MySQL, but it doesn't exist or is not accessible. A Unix socket file is used if you do not specify a host name or if you specify the special host name `localhost`. 

Make sure socket file exists (default `/tmp/mysql.sock`), check what path MySQL server uses.

Alternatively, use `127.0.0.1` as hostname to use TCP to connect to MySQL, but Unix socket file connection is faster than TCP/IP. 

https://dev.mysql.com/doc/refman/5.7/en/can-not-connect-to-server.html

https://stackoverflow.com/questions/20723803/pdoexception-sqlstatehy000-2002-no-such-file-or-directory
