### ISSUE TITLE
not sure why I'm not able to migrate

### ISSUE THREAD

**Issue by TacticsJan** [cakephp/phinx#1924]
Error: Wrong parameters for InvalidArgumentException([string $message [, long $code [, Throwable $previous = NULL]]]) in /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:83
Stack trace:
#0 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(83): Exception->__construct('There was a pro...', 'HYT00', Object(PDOException))
#1 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/SqlServerAdapter.php(101): Phinx\Db\Adapter\PdoAdapter->createPdoConnection('sqlsrv:server=,...', '', '', Array)
#2 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(149): Phinx\Db\Adapter\SqlServerAdapter->connect()
#3 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(209): Phinx\Db\Adapter\PdoAdapter->getConnection()
#4 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(225): Phinx\Db\Adapter\PdoAdapter->query('SELECT * FROM [...')
#5 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(363): Phinx\Db\Adapter\PdoAdapter->fetchAll('SELECT * FROM [...')
#6 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(335): Phinx\Db\Adapter\PdoAdapter->getVersionLog()
#7 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(204): Phinx\Db\Adapter\PdoAdapter->getVersions()
#8 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(255): Phinx\Db\Adapter\AdapterWrapper->getVersions()
#9 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(312): Phinx\Migration\Manager\Environment->getVersions()
#10 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(123): Phinx\Migration\Manager->migrate('kinderopvang', NULL, false)
#11 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(258): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(920): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(266): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(69): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(142): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#17 {main}

This is the error thrown when migrating. I don't really see what's wrong on my side. Help needed

**Comment by TacticsJan** [comment]
Apparently the $dsn doesn't get formed properly. This is what I get when I print out the $dsn in the catch:

sqlsrv:server=;database=;MultipleActiveResultSets=false

**Comment by TacticsJan** [comment]
Ok for some reason some of my env variables weren't being read out. So looks like an issue on my side. When I hardcoded host and name in phinx.php it all got to work again.

I'm gonna close this issue but someone should look into the arguments of the InvalidArgumentException that's being thrown.
