### ISSUE TITLE
Not deleted table if already exist

### ISSUE THREAD

**Issue by DionMontolalu** [cakephp/phinx#1998]
Hi Team, can help me ?

My problem is my code for delete table exist doesn't work.

**This my code :**
```
<?php
declare(strict_types=1);

use Phinx\Migration\AbstractMigration;

final class CreateTableNota extends AbstractMigration
{
    public function up()
    {
        $table = $this->table('tb_nota', array('id' => 'id_nota'));

        $table->addColumn('anggaran', 'float')
            ->addColumn('id_perusahaan', 'integer')
            ->addColumn('created_at', 'timestamp', ['default' => 'CURRENT_TIMESTAMP'])
            ->create();
    }

    public function down()
    {
        $exists = $this->hasTable('tb_nota');
        if ($exists) {
            $this->table('tb_nota')->drop()->save();
        }
    }
}
```

**This error messages:**
```
Phinx by CakePHP - https://phinx.org.

using config file phinx.php
using config parser php
using migration paths
 - C:\xampp\htdocs\db_nota_marina\db\migrations
using seed paths
 - C:\xampp\htdocs\db_nota_marina\db\seeds
using environment development
using adapter mysql
using database nota_marina
ordering by creation time

 == 20210629233142 CreateTableNota: migrating
PDOException: SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'tb_nota' already exists in C:\xampp\htdocs\db_nota_marina\vendor\robmorgan\phinx\src\Phinx\Db\Adapter\PdoAdapter.php:194
Stack trace:
#0 C:\xampp\htdocs\db_nota_marina\vendor\robmorgan\phinx\src\Phinx\Db\Adapter\PdoAdapter.php(194): PDO->exec('CREATE TABLE `t...')
#1 C:\xampp\htdocs\db_nota_marina\vendor\robmorgan\phinx\src\Phinx\Db\Adapter\MysqlAdapter.php(339): Phinx\Db\Adapter\PdoAdapter->execute('CREATE TABLE `t...')
#2 C:\xampp\htdocs\db_nota_marina\vendor\robmorgan\phinx\src\Phinx\Db\Adapter\AdapterWrapper.php(356): Phinx\Db\Adapter\MysqlAdapter->createTable(Object(Phinx\Db\Table\Table), Array, Array)
#3 C:\xampp\htdocs\db_nota_marina\vendor\robmorgan\phinx\src\Phinx\Db\Adapter\TimedOutputAdapter.php(114): Phinx\Db\Adapter\AdapterWrapper->createTable(Object(Phinx\Db\Table\Table),
Array, Array)
#4 C:\xampp\htdocs\db_nota_marina\vendor\robmorgan\phinx\src\Phinx\Db\Plan\Plan.php(148): Phinx\Db\Adapter\TimedOutputAdapter->createTable(Object(Phinx\Db\Table\Table), Array, Array)
#5 C:\xampp\htdocs\db_nota_marina\vendor\robmorgan\phinx\src\Phinx\Db\Table.php(722): Phinx\Db\Plan\Plan->execute(Object(Phinx\Db\Adapter\TimedOutputAdapter))
#6 C:\xampp\htdocs\db_nota_marina\vendor\robmorgan\phinx\src\Phinx\Db\Table.php(617): Phinx\Db\Table->executeActions(false)
#7 C:\xampp\htdocs\db_nota_marina\db\migrations\20210629233142_create_table_nota.php(19): Phinx\Db\Table->create()
#8 C:\xampp\htdocs\db_nota_marina\vendor\robmorgan\phinx\src\Phinx\Migration\Manager\Environment.php(112): CreateTableNota->up()
#9 C:\xampp\htdocs\db_nota_marina\vendor\robmorgan\phinx\src\Phinx\Migration\Manager.php(382): Phinx\Migration\Manager\Environment->executeMigration(Object(CreateTableNota), 'up', false)
#10 C:\xampp\htdocs\db_nota_marina\vendor\robmorgan\phinx\src\Phinx\Migration\Manager.php(356): Phinx\Migration\Manager->executeMigration('development', Object(CreateTableNota), 'up', false)
#11 C:\xampp\htdocs\db_nota_marina\vendor\robmorgan\phinx\src\Phinx\Console\Command\Migrate.php(123): Phinx\Migration\Manager->migrate('development', 20210629233142, false)
#12 C:\xampp\htdocs\db_nota_marina\vendor\symfony\console\Command\Command.php(299): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 C:\xampp\htdocs\db_nota_marina\vendor\symfony\console\Application.php(978): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 C:\xampp\htdocs\db_nota_marina\vendor\symfony\console\Application.php(295): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 C:\xampp\htdocs\db_nota_marina\vendor\robmorgan\phinx\src\Phinx\Console\PhinxApplication.php(69): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 C:\xampp\htdocs\db_nota_marina\vendor\symfony\console\Application.php(167): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 C:\xampp\htdocs\db_nota_marina\vendor\robmorgan\phinx\bin\phinx(28): Symfony\Component\Console\Application->run()
#18 {main}
```

**Comment by MasterOdin** [comment]
@DionMontolalu It looks like you're trying to do `phinx migrate` with the expectation that it'll run the `down` function? If you want to run the `down` function, you'll need to use `phinx rollback`, though you'll have to have previously successfully used a migration to roll it back. You can do `phinx migrate --fake` to skip actually running a migration, which would then allow you to run the rollback as desired:

```bash
$ phinx migrate --fake  # will mark CreateTableNota as being run without doing anything else
$ phinx rollback        # will run CreateTableNota::down and delete the tb_nota table as expected
```

**Comment by MasterOdin** [comment]
Closing this as this does not seem to be a bug with phinx itself.
