### ISSUE TITLE
0.12.8 introduced Postgres regression: cannot change boolean column's null option

### ISSUE THREAD

**Issue by airdrummingfool** [cakephp/phinx#2017]
Hello, and thanks for this great project.

My project uses Phinx for PostgreSQL migrations. After updating to `0.12.8` from `0.12.7`, the migrations started failing with the following error:

`PDOException: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: boolean = integer
LINE 1: ... "my_bool" TYPE BOOLEAN USING (CASE WHEN "my_bool"=0 THEN FA...`

After some investigation, I found that a migration that changed a `boolean` column so that it no longer allowed `null` values was no longer working. Here is a very simple example (boilerplate class code omitted, just `change` functions):

``` php
// migration0.php
public function change() {
    $this->table('my_table')->addColumn('my_bool', 'boolean', ['null' => true])->create();
}
```

``` php
// migration1.php
public function change() {
    $this->table('my_table')->changeColumn('my_bool', 'boolean', ['null' => false])->update();
}

```

The above example will work correctly on `0.12.7` and below, but fail with the above error on `0.12.8`.

<details>
<summary>Full error</summary>

```
PDOException: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: boolean = integer
LINE 1: ... "my_bool" TYPE BOOLEAN USING (CASE WHEN "my_bool"=0 THEN FA...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts. in /project/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:192
Stack trace:
#0 /project/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(192): PDO->exec('ALTER TABLE "pu...')
#1 /project/vendor/robmorgan/phinx/src/Phinx/Db/Util/AlterInstructions.php(108): Phinx\Db\Adapter\PdoAdapter->execute('ALTER TABLE "pu...')
#2 /project/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(608): Phinx\Db\Util\AlterInstructions->execute('ALTER TABLE "pu...', Array)
#3 /project/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(969): Phinx\Db\Adapter\PdoAdapter->executeAlterSteps('my_table', Object(Phinx\Db\Util\AlterInstructions))
#4 /project/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(484): Phinx\Db\Adapter\PdoAdapter->executeActions(Object(Phinx\Db\Table\Table), Array)
#5 /project/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TimedOutputAdapter.php(420): Phinx\Db\Adapter\AdapterWrapper->executeActions(Object(Phinx\Db\Table\Table), Array)
#6 /project/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(151): Phinx\Db\Adapter\TimedOutputAdapter->executeActions(Object(Phinx\Db\Table\Table), Array)
#7 /project/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(715): Phinx\Db\Plan\Plan->execute(Object(Phinx\Db\Adapter\TimedOutputAdapter))
#8 /project/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(623): Phinx\Db\Table->executeActions(true)
#9 /project/db/migrations/20161123235506_migration1.php(9): Phinx\Db\Table->update()
#10 /project/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(108): Migration1->change()
#11 /project/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(376): Phinx\Migration\Manager\Environment->executeMigration(Object(Migration1), 'up', false)
#12 /project/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(351): Phinx\Migration\Manager->executeMigration('test', Object(Migration1), 'up', false)
#13 /project/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate('test', 20161123235506, false)
#14 /project/vendor/symfony/console/Command/Command.php(299): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /project/vendor/symfony/console/Application.php(978): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /project/vendor/symfony/console/Application.php(295): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /project/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(68): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /project/vendor/symfony/console/Application.php(167): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /project/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#20 {main}
```

</details>

**Comment by MasterOdin** [comment]
Introduced in #1974. I think we've hit the limit of what we can do in Phinx without having it query for table structure before doing the migration step.
