### ISSUE TITLE
migration create command is not creating required folders

### ISSUE THREAD

**Issue by nook24** [cakephp/phinx#2105]
Howdy
Not sure if this is the right place for this issue. Anyway I noticed that the `migration create` command is not creating the required folders anymore:
```
$ bin/cake migrations create -p FooModule Initial
using migration paths
using seed paths
PHP Fatal error:  Uncaught Exception: You probably used curly braces to define migration path in your Phinx configuration file, but no directories have been matched using this pattern. You need to create a migration directory manually. in /opt/openitc/frontend/vendor/robmorgan/phinx/src/Phinx/Console/Command/Create.php:111
Stack trace:
#0 /opt/openitc/frontend/vendor/robmorgan/phinx/src/Phinx/Console/Command/Create.php(144): Phinx\Console\Command\Create->getMigrationPath()
#1 /opt/openitc/frontend/vendor/cakephp/migrations/src/Command/Phinx/CommandTrait.php(37): Phinx\Console\Command\Create->execute()
#2 /opt/openitc/frontend/vendor/cakephp/migrations/src/Command/Phinx/Create.php(75): Migrations\Command\Phinx\Create->parentExecute()
#3 /opt/openitc/frontend/vendor/symfony/console/Command/Command.php(308): Migrations\Command\Phinx\Create->execute()
#4 /opt/openitc/frontend/vendor/symfony/console/Application.php(1002): Symfony\Component\Console\Command\Command->run()
#5 /opt/openitc/frontend/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#6 /opt/openitc/frontend/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#7 /opt/openitc/frontend/vendor/cakephp/migrations/src/Command/MigrationsCommand.php(126): Symfony\Component\Console\Application->run()
#8 /opt/openitc/frontend/vendor/cakephp/cakephp/src/Console/BaseCommand.php(189): Migrations\Command\MigrationsCommand->execute()
#9 /opt/openitc/frontend/vendor/cakephp/migrations/src/Command/MigrationsCommand.php(198): Cake\Console\BaseCommand->run()
#10 /opt/openitc/frontend/vendor/cakephp/cakephp/src/Console/CommandRunner.php(334): Migrations\Command\MigrationsCommand->run()
#11 /opt/openitc/frontend/vendor/cakephp/cakephp/src/Console/CommandRunner.php(172): Cake\Console\CommandRunner->runCommand()
#12 /opt/openitc/frontend/bin/cake.php(12): Cake\Console\CommandRunner->run()
#13 {main}
  thrown in /opt/openitc/frontend/vendor/robmorgan/phinx/src/Phinx/Console/Command/Create.php on line 111
```

To resolve the issue, i simply created the two folders:
```
mkdir -p plugins/FooModule/config/Migrations
mkdir -p plugins/FooModule/config/Seeds
```

I'm on CakePHP 4.4.5 using the cakephp/migrations 3.5.3
Would be good if the migration plugin would create all required folders by itself again.

**Comment by nook24** [comment]
I have moved this issue to https://github.com/cakephp/migrations/issues/565
