### ISSUE TITLE
Duplicate migration with version "2147483647"

### ISSUE THREAD

**Issue by JankesPWT** [cakephp/phinx#2192]
I keep getting Duplicate migration error. I'm using 32bit system and that 2147483647 number as migraton version shows up.
Is there any solution?

```
InvalidArgumentException: Duplicate migration - "C:\Users\janke\Desktop\pwtsoftware\migrejszyn/migrations\20230418121131_squad.php" has the same version as "2147483647" in C:\Users\janke\Desktop\pwtsoftware\migrejszyn\vendor\robmorgan\phinx\src\Phinx\Migration\Manager.php:783

Stack trace:

#0 C:\Users\janke\Desktop\pwtsoftware\migrejszyn\vendor\robmorgan\phinx\src\Phinx\Migration\Manager.php(313): Phinx\Migration\Manager->getMigrations('development')

#1 C:\Users\janke\Desktop\pwtsoftware\migrejszyn\vendor\robmorgan\phinx\src\Phinx\Console\Command\Migrate.php(122): Phinx\Migration\Manager->migrate('development', NULL, false)

#2 C:\Users\janke\Desktop\pwtsoftware\migrejszyn\vendor\symfony\console\Command\Command.php(312): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#3 C:\Users\janke\Desktop\pwtsoftware\migrejszyn\vendor\symfony\console\Application.php(1022): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#4 C:\Users\janke\Desktop\pwtsoftware\migrejszyn\vendor\symfony\console\Application.php(314): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#5 C:\Users\janke\Desktop\pwtsoftware\migrejszyn\vendor\robmorgan\phinx\src\Phinx\Console\PhinxApplication.php(70): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 

#6 C:\Users\janke\Desktop\pwtsoftware\migrejszyn\vendor\symfony\console\Application.php(168): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#7 C:\Users\janke\Desktop\pwtsoftware\migrejszyn\vendor\robmorgan\phinx\bin\phinx(28): Symfony\Component\Console\Application->run()   

#8 C:\Users\janke\Desktop\pwtsoftware\migrejszyn\vendor\bin\phinx(120): include('C:\\Users\\janke\\...')

#9 {main}
```

**Comment by dereuromark** [comment]
Do not use 32bit system
See https://github.com/cakephp/phinx/pull/2169
